# This is a basic workflow to help you get started with Actions

name: Update Rules

# Controls when the workflow will run
on:
  schedule:
    - cron: '0 0/6 * * *'

  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "update-rules"
  update-rules:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@main

      # Install hostlist-compiler (https://github.com/AdguardTeam/HostlistCompiler)
      - name: Install hostlist-compiler
        run: npm i -g @adguard/hostlist-compiler

      - name: Download Rules
        run: |
          cd sources/AdGuardHome
          wget https://raw.githubusercontent.com/hacamer/AGHRules/main/regex.txt
          wget https://adguardteam.github.io/HostlistsRegistry/assets/filter_1.txt
          wget https://adguardteam.github.io/HostlistsRegistry/assets/filter_2.txt
          wget https://adguardteam.github.io/HostlistsRegistry/assets/filter_7.txt
          wget https://adguardteam.github.io/HostlistsRegistry/assets/filter_8.txt
          wget https://adguardteam.github.io/HostlistsRegistry/assets/filter_9.txt
          wget https://adguardteam.github.io/HostlistsRegistry/assets/filter_11.txt
          wget https://adguardteam.github.io/HostlistsRegistry/assets/filter_12.txt
          wget https://adguardteam.github.io/HostlistsRegistry/assets/filter_23.txt
          wget https://adguardteam.github.io/HostlistsRegistry/assets/filter_27.txt
          wget https://adguardteam.github.io/HostlistsRegistry/assets/filter_29.txt
          wget https://adguardteam.github.io/HostlistsRegistry/assets/filter_30.txt
          wget https://adguardteam.github.io/HostlistsRegistry/assets/filter_33.txt
          wget https://raw.githubusercontent.com/neodevpro/neodevhost/master/adblocker
          wget https://o0.pages.dev/Xtra/adblock.txt
          cd ../../

      # Build a configurable blocklist from multiple sources (AdGuard Home)
      - name: Build a blocklist
        run: |
          cd sources/AdGuardHome
          hostlist-compiler -c "../../configuration/AdGuardHome/configuration.json" -o "../../output/AdGuardHome/output.txt"
          cd ../../

      # Push a commit using the built-in token
      - name: Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Update at $(TZ=UTC-8 date +"%Y-%m-%d %H:%M")"
          git push
