# https://github.com/Cats-Team/AdRules/blob/script/.github/workflows/desize.yml
name: desize
on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  clean:
    runs-on: ubuntu-latest
      
    steps:
      - name: Clone repo
        run: git clone --mirror https://github.com/RWTighnari/HostListCompilation.git repo_gh
          
      - name: Clean up
        run: |
          curl -fsSL -o bfg.jar https://repo1.maven.org/maven2/com/madgag/bfg/1.14.0/bfg-1.14.0.jar && \
          java -jar bfg.jar --strip-blobs-bigger-than 10K -fs 100M repo_gh && \
          cd repo_gh && \
          git reflog expire --expire=now --all && \
          git gc --prune=now --aggressive
          
      - name: Push
        run: |
          cd repo_gh
          git show-ref | cut -d' ' -f2 | grep 'pull' | xargs -r -L1 git update-ref -d
          git push origin --force
          cd ../
          rm -rf repo_gh
